window.TDG_ARCHIVE = {
  groups: [
    {
      id: "product",
      title: "产品",
      projectIds: ["01", "02", "03", "04", "05", "06", "07"],
    },
    {
      id: "ui",
      title: "UI",
      projectIds: ["08", "09", "10", "11", "12", "13", "14", "15"],
    },
    {
      id: "rendering",
      title: "视觉渲染",
      projectIds: ["16", "17", "18", "19", "20"],
    },
  ],
  projects: [
    {
      id: "01",
      title: "大地探索家",
      year: "2024",
      tagline: "Lighting / Field Kit / Industrial Design",
      description:
        "兼顾了户外探索的照明安全与专业拍摄的补光需求，在严苛环境下为摄影师提供可靠保障与精准的创作支持。",
      imageFolder: "./Assets/Project 01",
      embedSrc: "./projects/project-01/?embed=1",
      visible: true,
    },
    {
      id: "02",
      title: "针迹",
      year: "2023",
      tagline: "Wearable Hardware / Labor Narrative",
      description:
        "通过可穿戴硬件记录外卖骑手的劳动轨迹与个人叙事，以此对抗算法系统的“隐形化”困境，并重塑其在数字化时代下的个体尊严与社会价值。",
      imageFolder: "./Assets/Project 02",
      embedSrc: "./projects/project-02/?embed=1",
      visible: true,
    },
    {
      id: "03",
      title: "乌托邦：水上静居",
      year: "2023",
      tagline: "Concept Yacht / Marine Living",
      description:
        "受逆戟鲸仿生美学启发的先锋居住空间概念游艇。在 20 米级船身内平衡了极致的动力学流线外观与现代居住空间，探索了未来海上生活的新形态。",
      imageFolder: "./Assets/Project 03",
      embedSrc: "./projects/project-03/?embed=1",
      visible: true,
    },
    {
      id: "04",
      title: "气：风场交互座舱",
      year: "2022",
      tagline: "Interaction Design / Cockpit UX",
      description:
        "探索以气流为交互媒介的未来座舱方案。通过定向气流将信息转化为身体的本能反馈，解决了辅助驾驶中人机感官疏离的问题，实现了更具直觉性的感官闭环。",
      imageFolder: "./Assets/Project 04",
      embedSrc: "./projects/project-04/?embed=1",
      visible: true,
    },
    {
      id: "05",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "06",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "07",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "08",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "09",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "10",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "11",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "12",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "13",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "14",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "15",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "16",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "17",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "18",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "19",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
    {
      id: "20",
      title: "待添加项目",
      year: "TBD",
      tagline: "Placeholder / Future Entry",
      description: "这里预留给后续加入的项目内容与主图。",
      imageFolder: "",
      placeholder: true,
      visible: true,
    },
  ],
};
